packages:
  - corpSetup/c25cloudfront/source/authGuardLambdaEdge
  - corpSetup/c25cloudfront/source/loginApp
  - selfService/web
  - selfService/backend
injectWorkspacePackages: true
allowBuilds:
  esbuild: true
  azure-functions-core-tools: true
onlyBuiltDependencies:
  - esbuild
  - azure-functions-core-tools
