#!/usr/bin/env sh
cd "$(git rev-parse --show-toplevel)"

BRANCH="$(git rev-parse --abbrev-ref HEAD)"

# Checks for all branches

# Extra checks only on main
if [ "$BRANCH" = "main" ]; then
  echo "Running main-only pre-commit checks..."
  npx lint-staged --config .codingstandards/lint-staged.config.mjs --relative --no-stash
  # add more main-only commands here
fi
